apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hello-okteto.fullname" . }}
  labels:
    app: "{{ template "hello-okteto.fullname" . }}"
    chart: "{{ template "hello-okteto.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-okteto.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-okteto.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: okteto/hello-okteto:golang
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP